### ISSUE TITLE
Erreur lors de l'export

### ISSUE THREAD

**Issue by julienfastre** [Champs-Libres/QgisGeoJSONExportPlugin#1]
J'ai ajouté une couche shapefile, en 31370.

j'ai lancé l'export. Voici le message d'erreur : 

```
Une erreur est apparue lors de l'exécution du code Python :


Traceback (most recent call last):
  File "/home/user/.qgis2/python/plugins/GeoJSONPlugin/gjsepdialog.py", line 265, in export
    self.json_file_generation()
  File "/home/user/.qgis2/python/plugins/GeoJSONPlugin/gjsepdialog.py", line 150, in json_file_generation
    self.tmp_folder_path, layer_name + '_alias.json'))
  File "/home/user/.qgis2/python/plugins/GeoJSONPlugin/gjsepdialog.py", line 122, in create_json_alias_file
    f = open(filename, 'w')
IOError: [Errno 2] Aucun fichier ou dossier de ce type: u'/media/ssd2/julien/dev/QgisGeoJSONExportPlugin/tmp/Lignes_2014-04_31370_alias.json'


Version de Python :
2.7.8 (default, Oct 20 2014, 15:08:52) 
[GCC 4.9.1]


Version de QGIS :
2.6.0-Brighton Brighton, exported

Chemin vers Python : ['/usr/share/qgis/python/plugins/processing', '/usr/share/qgis/python', u'/home/user/.qgis2/python', u'/home/user/.qgis2/python/plugins', '/usr/share/qgis/python/plugins', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/PILcompat', '/usr/lib/python2.7/dist-packages/gtk-2.0', '/usr/lib/pymodules/python2.7', '/usr/lib/python2.7/dist-packages/ubuntu-sso-client', '/home/user/.qgis2/python/plugins/MetaSearch/ext-libs', '/home/user/.qgis2/python/plugins/mmqgis/forms', '/usr/share/qgis/python/plugins/fTools/tools']
```

**Comment by julienfastre** [comment]
Je pense que ça vient du chemin lors de l'export : il veut créer un fichier temporaire dans QgisGeoJSONExport, mais j'ai installé dans GeoJSONPlugin

**Comment by julienfastre** [comment]
C'est bien ça: il faut que le plugin soit installé dans le répertoire qui porte le bon nom **ET** il faut que le dossier  `tmp` ait été créé.

N'est-il pas possible d'utiliser le dossier temporaire du système (`/tmp` sous linux) ?

Ou alors, de repérer le chemin d'installation ? (`pwd`)

**Comment by marcu** [comment]
Le code utilise déjà le `pwd`. A mon avis ça vient du fait que le fichier tmp n'existait pas. A l'ouverture de la fenêtre de dialogue, il est maintenant vérifié que le répertoire existe bien et si ce n'est pas le cas, il est créé.
