### ISSUE TITLE
qgis 2.9.0-Master error loading plugin

### ISSUE THREAD

**Issue by marcobra** [Champs-Libres/QgisGeoJSONExportPlugin#7]
Hi today in my system (*\* see below )i get this error starting qgis plugin:

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 219, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/ubuntu/.qgis2/python/plugins/QgisGeoJSONExportPlugin/**init**.py", line 26, in classFactory
    from gjsep import GeoJSONExportPlugin
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/ubuntu/.qgis2/python/plugins/QgisGeoJSONExportPlugin/gjsep.py", line 33, in 
    from gjsepdialog import GeoJSONExportPluginDialog
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/ubuntu/.qgis2/python/plugins/QgisGeoJSONExportPlugin/gjsepdialog.py", line 28, in 
    from processing.ui.ui_DlgConfig import Ui_DlgConfig
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: No module named ui.ui_DlgConfig

(**)  Ubuntu Qgis installed (nightly release):

qgis:
  Installato: 1:2.9.0+git20150604+385529e+20trusty-ubuntugis
  Candidato:  1:2.9.0+git20150604+385529e+20trusty-ubuntugis
  Tabella versione:
 **\* 1:2.9.0+git20150604+385529e+20trusty-ubuntugis 0
        500 http://qgis.org/ubuntugis-nightly/ trusty/main amd64 Packages
        100 /var/lib/dpkg/status
     2.0.1-2build2 0
        500 http://archive.ubuntu.com/ubuntu/ trusty/universe amd64 Packages

**Comment by marcu** [comment]
Thanks for the report.

I think the problem was that the code was trying to load the processing plugin (which is not needed). I remove this dependency.

I updated the version of the plugin. Does it work now ?

**Comment by marcobra** [comment]
Still error on installing... (cannot install)
No module named ui.ui_DlgConfig

But downloading from github do not get more error...

**Comment by marcu** [comment]
Can you retry ? The good version is the 0.1.6 one.

**Comment by marcobra** [comment]
now is working 
thanks
